### ISSUE TITLE
/public/index.html

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/radio_logger#10]
This page needs a lot of work to be any good.

This needs to be the page that loads at `/` root or `index.html`

Ideas for this was:

- a splash page after initial app load
- Access to the dashboard once logged in and authenticated
- Load the Signup and/or Signin page if the user is new (not registered)

not sure about the rest.. Ideas?

**Comment by gbowne1** [comment]
@krishan-here

**Comment by TechLateef** [comment]
Let me look into this but am more of backend

**Comment by gbowne1** [comment]
Ok.  I figured we woukd use MongoDB for now.  I have my local DB as 'radiologger".

I opened a discussion.

**Comment by gbowne1** [comment]
This is pretty much completed with recent commits/push. Closing as completed.
