### ISSUE TITLE
setup project and run server

### ISSUE THREAD

**Issue by krishan-here** [gbowne1/radio_logger#11]
i am done with setup project, but for running server properly i have to comment these code(attach a screenshot).Can you please tell me why did you write these code which i comment.
<img width="581" alt="image" src="https://user-images.githubusercontent.com/82387829/187931533-1f37ffc6-f670-48fc-ad12-ec611eefd7f5.png">

**Comment by gbowne1** [comment]
This code was left over from an old project.

**Comment by gbowne1** [comment]
Routing requirements are in another issue.

**Comment by krishan-here** [comment]
Can you assign this to me. I want to fix this.

**Comment by gbowne1** [comment]
ok @krishan-here.  Let me know if you need to know what routes where..

**Comment by gbowne1** [comment]
https://github.com/gbowne1/radio_logger/issues/3 these are the main ones I think.
