### ISSUE TITLE
Fix Express routes

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/radio_logger#3]
needs Express routing in server.js for 

All these  components are in /src/client/src/components folder

- Dashboard /dashboard (dashboard.html)
- Contest Log /contestlog (contestlog.html)
- Shortwave Log /swllog (swllog.html)
- Signin /signin  (signin.html)
- Ham Log /hamlog (hamlog.html)
- Signup /signup (signup) 

Make sure that the routes exist in the Dashboard and go to the correct component when the button is clicked.

**Comment by krishan-here** [comment]
assign this to me. i will work on this.

**Comment by gbowne1** [comment]
@krishan-here I have assigned you

**Comment by gbowne1** [comment]
@krishan-here still has some issues.

Now the pics do not appear in the cards on dashboard

Appears not able to pick up the scripts and styles something about MIME type.

**Comment by krishan-here** [comment]
okay working on it.
