### ISSUE TITLE
Node/Express server not sending CSS and JS files

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/radio_logger#37]
Node Express server not sending CSS and JS files.

Server may need to be altered to include:

```javascript
app.get('/', function(req, res) {
    if(req.url == "/" || req.url == "/main.html"){
res.sendFile('/main.html', { root : __dirname})
}else if(req.url == "/mainstyle.css"){
res.sendFile('mainstyle.css', { root : __dirname})
}
});
```

**Comment by gbowne1** [comment]
Expect to see a number of cannot GET / and 404 in the browser console pointing to the CSS/JS files.

**Comment by krishan-here** [comment]
@gbowne1  can you mention which files are not rendering?

**Comment by gbowne1** [comment]
@krishan-here 

Hang on let me test again.

**Comment by gbowne1** [comment]
I'm pretty sure it was at least vhflog.

**Comment by gbowne1** [comment]
I think the routing is all messed up.

I know clicking on the buttons on the dashboard returns cannot GET....

The pics also used to display as well...

@TechLateef

**Comment by gbowne1** [comment]
I believe this is fixed.. closing this but there are larger issues with this app.
