### ISSUE TITLE
Server not starting

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/radio_logger#38]
server no longer starts with npm start or node server.js and nodemon is not working either.

**Comment by gbowne1** [comment]
Does this work so I can close @TechLateef ?

Its currently overnight here in the US wont be able to trst for at least another 12hr from now

**Comment by TechLateef** [comment]
It's working now

**Comment by gbowne1** [comment]
Ok. Will close this.  Thanks.  

I also dont remember if the signup login & register was working.  Its been ~6 momths since I looked at any of this.  

The login is index.html

**Comment by TechLateef** [comment]
okay i will check that out my love for backend dont allow me to check into all that lol

**Comment by gbowne1** [comment]
Sure thing.  I like to do both but my CSS isnt very strong.  Im sure we will find people to fill in the blanks.

I wanna get this to MVP by the end of the year.  

I also tried twice in react..  http://github.com/gbowne1/radio-logger and also another try in http://github.com/gbowne1/RadioLogger both of those have piles of junk files I was trying when I was new to React.
