### ISSUE TITLE
npm start // server.js issue with MongoDB

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/radio_logger#42]
I am getting:

```
$ npm start

> y@0.0.1 start
> node server.js

Up and Running on port 3000
(node:14634) [MONGOOSE] DeprecationWarning: Mongoose: the `strictQuery` option will be switched back to `false` by default in Mongoose 7. Use `mongoose.set('strictQuery', false);` if you want to prepare for this change. Or use `mongoose.set('strictQuery', true);` to suppress this warning.
(Use `node --trace-deprecation ...` to show where the warning was created)
Connected to MongoDB
```

$ mongod --version
db version v4.4.18
Build Info: {
    "version": "4.4.18",
    "gitVersion": "8ed32b5c2c68ebe7f8ae2ebe8d23f36037a17dea",
    "openSSLVersion": "OpenSSL 1.1.1n  15 Mar 2022",
    "modules": [],
    "allocator": "tcmalloc",
    "environment": {
        "distmod": "debian10",
        "distarch": "x86_64",
        "target_arch": "x86_64"
    }
}
---
$ mongo --version
MongoDB shell version v4.4.18
Build Info: {
    "version": "4.4.18",
    "gitVersion": "8ed32b5c2c68ebe7f8ae2ebe8d23f36037a17dea",
    "openSSLVersion": "OpenSSL 1.1.1n  15 Mar 2022",
    "modules": [],
    "allocator": "tcmalloc",
    "environment": {
        "distmod": "debian10",
        "distarch": "x86_64",
        "target_arch": "x86_64"
    }
}

**Comment by TechLateef** [comment]
yes this not an issue i will just stop it from showing that i need to include something before connecting

**Comment by gbowne1** [comment]
Ahh ok.. I was wondering.  It does connect though, unless you have something else running on 3000.  It doesnt ask you if youd like to choose the next available port though, like the react dev server does.. although to be fair, mongo doesn't either so..

**Comment by TechLateef** [comment]
yes
